---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
    - e4f3e15eb852b314700a13f75297bf4d
    - 1359099b9d434ee2c7cfbde47dc72de0
    - 4ea8362a2a69b1e9bbcacc43c7fd5245
    - 65e08eaad147b579e252cf8af81b02fa
    - dc598e1038cecf0eac28474c64166b6b
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
